### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by ShixiangWang** [njaupan/ECDNA#20]
Any suggestions?

Use map:

```
fastp --thread 20 -i /data3/wsx/share/HGC20230203003-0001/SNU16-HMW_R1_001.fastq.gz -I /data3/wsx/share/HGC20230203003-0001/SNU16-HMW_R2_001.fastq.gz -o /data3/wsx/ecc_finder_Results/SNU16-HMW.R1.fastq.gz -O /data3/wsx/ecc_finder_Results/SNU16-HMW.R2.fastq.gz -h /data3/wsx/ecc_finder_Results/SNU16-HMW.html
fastp v0.23.2, time used: 317 seconds
Fri Feb 17 16:25:15 2023 --- INFO: Run assembmy mode at a wide range of k-mer sizes, evaluating the graph at each one
Fri Feb 17 16:25:15 2023 --- INFO: Which will be the most time-comsuming

Starting Unicycler (2023-02-17 16:25:15)
    Welcome to Unicycler, an assembly pipeline for bacterial genomes. Since you provided only short reads, Unicycler will essentially function as a
SPAdes-optimiser. It will try many k-mer sizes, choose the best based on contig length and graph connectivity, and scaffold the graph using SPAdes
repeat resolution.
    For more information, please see https://github.com/rrwick/Unicycler

Command: /data3/wsx/miniconda3/envs/circlemap/bin/unicycler -1 /data3/wsx/ecc_finder_Results/SNU16-HMW.R1.fastq.gz -2 /data3/wsx/ecc_finder_Results/SNU16-HMW.R2.fastq.gz -t 20 --min_fasta_length 8 --keep 0 -o /data3/wsx/ecc_finder_Results/

Unicycler version: v0.5.0
Using 20 threads

The output directory already exists and files may be reused or overwritten:
  /data3/wsx/ecc_finder_Results

Dependencies:
  Program       Version   Status
  spades.py     3.15.5    good
  racon                   not used
  makeblastdb   2.13.0+   good
  tblastn       2.13.0+   good


Choosing k-mer range for assembly (2023-02-17 16:33:33)
    Unicycler chooses a k-mer range for SPAdes based on the length of the input reads. It uses a wide range of many k-mer sizes to maximise the
chance of finding an ideal assembly.

SPAdes maximum k-mer: 127
Median read length: 150
K-mer range: 27, 53, 71, 87, 99, 111, 119, 127


SPAdes assemblies (2023-02-17 16:41:59)
    Unicycler now uses SPAdes to assemble the short reads. It scores the assembly graph for each k-mer using the number of contigs (fewer is
better) and the number of dead ends (fewer is better). The score function is 1/(c*(d+2)), where c is the contig count and d is the dead end count.

spades.py -o /data3/wsx/ecc_finder_Results/spades_assembly -k 27 --threads 20 --isolate -1 /data3/wsx/ecc_finder_Results/SNU16-HMW.R1.fastq.gz -2 /data3/wsx/ecc_finder_Results/SNU16-HMW.R2.fastq.gz -m 1024
Error: SPAdes encountered an error:

mv: cannot stat ‘/data3/wsx/ecc_finder_Results/assembly.fasta’: No such file or directory
Fri Feb 17 20:45:59 2023 --- INFO: Finished running ecc_finder
Fri Feb 17 20:45:59 2023 --- INFO: Goodbye, have a nice day!
```

Use assembly.

```
Sat Feb 18 12:08:15 2023 --- VERSION: ecc_finder v1.0.0
Sat Feb 18 12:08:15 2023 --- CMD: python ecc_finder.py map-sr /data1/database/human/hg38/genome.fa /data3/wsx/share/HGC20230203003-0001/SNU16-HMW_R1_001.fastq.gz /data3/wsx/share/HGC20230203003-0001/SNU16-HMW_R2_001.fastq.gz -r /data1/database/human/hg38/genome.fa -t 20 -o /data3/wsx/ecc_finder_Results -x SNU16-HMW
Sat Feb 18 12:08:15 2023 --- INFO: Remove adapter
Sat Feb 18 12:08:15 2023 --- INFO: Retaining pre-existing file: /data3/wsx/ecc_finder_Results/align_files/SNU16-HMW.html
Sat Feb 18 12:08:15 2023 --- INFO: Align the query raw read to the reference
<eccFinder_lib.Aligner.bwaAligner object at 0x7fe5bf85bb50>
Sat Feb 18 12:08:15 2023 --- INFO: Retaining pre-existing file: /data3/wsx/ecc_finder_Results/align_files/SNU16-HMW.sam
Sat Feb 18 12:08:15 2023 --- INFO: Sort the alignments
Sat Feb 18 12:08:15 2023 --- INFO: Retaining pre-existing file: /data3/wsx/ecc_finder_Results/align_files/SNU16-HMW.bam
Sat Feb 18 12:08:15 2023 --- INFO: Check read pair and read pair orientation
Sat Feb 18 12:08:15 2023 --- INFO: Retaining pre-existing file: /data3/wsx/ecc_finder_Results/align_files/SNU16-HMW.bam.bed
Sat Feb 18 12:08:15 2023 --- INFO: Detecting sites of genomic enrichment
Sat Feb 18 12:08:15 2023 --- INFO: Retaining pre-existing file: /data3/wsx/ecc_finder_Results/SNU16-HMW.site.bed
Sat Feb 18 12:08:15 2023 --- INFO: Detect split reads
Traceback (most recent call last):
  File "/data3/wsx/ecc_finder/map-sr.py", line 380, in <module>
    main()
  File "/data3/wsx/ecc_finder/map-sr.py", line 353, in main
    run_split(file_prefix,align_path,peak_path, num_threads, overwrite_files)
  File "/data3/wsx/ecc_finder/map-sr.py", line 128, in run_split
    d =BedTool.merge(x,c = '5,6', o = 'collapse,collapse')
  File "/data3/wsx/miniconda3/envs/circlemap/lib/python3.8/site-packages/pybedtools/bedtool.py", line 923, in decorated
    result = method(self, *args, **kwargs)
  File "/data3/wsx/miniconda3/envs/circlemap/lib/python3.8/site-packages/pybedtools/bedtool.py", line 402, in wrapped
    stream = call_bedtools(
  File "/data3/wsx/miniconda3/envs/circlemap/lib/python3.8/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools merge -o collapse,collapse -i /data3/wsx/TEMPDIR/pybedtools.fcckufbt.tmp -c 5,6

Error message was:

*****
***** ERROR: Requested column 5, but database file /data3/wsx/TEMPDIR/pybedtools.fcckufbt.tmp only has fields 1 - 0.
```

**Comment by Li-jiale** [comment]
Hi, my analysis is also stuck at the Detect split reads stage. I would like to ask if you have solved this problem later. Sincerely, Jiale
