### ISSUE TITLE
Missing output files

### ISSUE THREAD

**Issue by nemitheasura** [njaupan/ECDNA#6]
Hello,

i ran ecc_finder on my illumina seq data (in conda env, as suggested in manual site). The pipeline produced 2 output folders: align_files and peak_files and ecc.sr.site.bed file. I have noticed that .png file .fasta file and .csv file are missing. 

Also, I have noticed that the test data produced an empty .csv and .png (there were no data within the plot, plotting area was empty) - due to the lack of provided reference genome, I used TAIR10. 

Here is my console output - I tried to rerun the command, and it seems like it gets stuck at split read detection step. 

`
Tue Feb  1 11:07:26 2022 --- CMD: python ecc_finder.py map-sr reference.fasta.mmidx FKDL202584971-1a-N706-AK425_H7W3WCCX2_L1_1.fq FKDL202584971-1a-N706-AK425_H7W3WCCX2_L1_2.fq -r reference.fasta --aligner minimap2 -o ecc_finder/ecc_finder_minimap2
Tue Feb  1 11:07:26 2022 --- INFO: Remove adapter
Tue Feb  1 11:07:26 2022 --- INFO: Retaining pre-existing file: ecc_finder/ecc_finder_minimap2/align_files/ecc.sr.html
Tue Feb  1 11:07:26 2022 --- INFO: Align the query raw read to the reference
Tue Feb  1 11:07:26 2022 --- INFO: Retaining pre-existing file: ecc_finder/ecc_finder_minimap2/align_files/ecc.sr.sam
Tue Feb  1 11:07:26 2022 --- INFO: Sort the alignments
Tue Feb  1 11:07:26 2022 --- INFO: Retaining pre-existing file: ecc_finder/ecc_finder_minimap2/ecc.sr.bam
Tue Feb  1 11:07:26 2022 --- INFO: Check read pair and read pair orientation
Tue Feb  1 11:07:26 2022 --- INFO: Retaining pre-existing file: ecc_finder/ecc_finder_minimap2/ecc.sr.bam.bed
Tue Feb  1 11:07:26 2022 --- INFO: Detecting sites of genomic enrichment
Tue Feb  1 11:07:26 2022 --- INFO: Retaining pre-existing file: ecc_finder/ecc_finder_minimap2/ecc.sr.site.bed
Tue Feb  1 11:07:26 2022 --- INFO: Detect split reads
(ecc_finder) nemi@theasura-mint:~/ecc_finder$ 
`

Could you provide any info/support on that matter?

Best,
Nemi

**Comment by njaupan** [comment]
Dear Nemi,

It is weird that it gets empty from test data, something definitely get
wrong because everything should run successfully as indicated from YouTube
videos.
Can you attach screenshot of your terminal or script?
Best regards

**Comment by nemitheasura** [comment]
Hi,
currently I am rerunning the pipe with less workers. This time the error did not ocurred yet - it is at the minimap2 stage, so there is nothing in the console which would be worth looking at. I cannot provide you the screenshot from the previous run, because it crashed the server, so it needed to be restarted. RIP to my byobu session. 

This was the culprit:

`python ecc_finder.py map-sr reference.fasta.mmidx FKDL202584971-1a-N706-AK425_H7W3WCCX2_L1_1.fq FKDL202584971-1a-N706-AK425_H7W3WCCX2_L1_2.fq -r reference.fasta --aligner minimap2 -o ecc_finder/ecc_finder_minimap2 -t 16`

The input fastqs are a bit large, circa 30GB each (yes, eccDNA enriched, just full capacity sequencing run). 

I have noticed that it quickly starts to occupy an entire RAM (well, I have >200 GB at my disposal, so it is definitely a quite fine amount I think). And it crashes at the "Detect split reads" stage. Funny thing is, that it does not throw an error. I figured out that there must be something wrong because there was a description of the *.csv file in the manual. Also when I ran the analysis on the test data, it was clear to me that some outputs are really missing. 

We enlarged our /tmp folder and decreased the amount of workers used (initially I ran this with 16 cores, but this time there ara only 5. This is why the entire analysis goes really slow. 

I will keep you updated - if this would appear again. 

Maybe it would be worth to consider, whether the tool could be optimized to work on larger data? 

Best,
Nemi

**Comment by njaupan** [comment]
Thank you for the details.
Given any large data, it won’t be a problem for minimap2 to run alignment. However, as you indicated large RAM issue in the imitation mode, I realized it is from bedtools which used to detect split and discordant reads.

I have compared the performance of Samblaster and bedtools for this step,samblaster consequently speeded up and took less computational memory but circular reads is less detected. Given your data of high coverage, circular reads should have significant high copy numbers and then samblaster should be a better choice. It can be added to new version.

One thing of empty file is that when you rerun the same script, it will continue to next step if it found file with the same prefix name. In order to skip the alignment step and only use the successfully produced bam file,
I would suggest you to 1) delete the folder of peak_files and empty failed file or 2) add different prefix name by “ -x  “ and rename bam file so you don’t need to rerun alignment.

Best wishes

>

**Comment by nemitheasura** [comment]
Thank you for your reply. 

I wonder, because I have found a following workaround: if I split my read files into chunks and run a chunk, then I retrieve a correct output - all of the files, with the extensions expected. Can I run it in chunks and merge the outputs? Would this final output be legit?

Looking forward for hearing from you. 
Have a nice day!

Best,
Nemi

**Comment by njaupan** [comment]
Hi Nemi,

I haven't tried this way, but it definitely will work for most of significant circular DNAs.

I would suggest after merging csv files of chunks into one, check top 5 locations with high supported reads. Circular DNA arising from repetitive sequences such as ribosomal DNA, centromere or telomere will be the possible controls, the remaining locations will be final interest.

To balance the trade off between abundance and accuracy of merged csv file, you could give a try to plot read number distribution, based on that set a decent threshold to remove location with low number supported reads.

Let me know it helps or not.

Best regards,
Panpan

**Comment by nemitheasura** [comment]
Hi @njaupan, 
before I tried to run your program on splitted files, I launched it on the another server - with 1TB temp folder and 1008 GB RAM. Everything ran smoothly until it reached the "Detect split reads step".  Then it crashed. 
The output from my console is shown below:

```
Sun Feb  6 19:49:18 2022 --- INFO: Detect split reads
Traceback (most recent call last):
  File "map-sr.py", line 380, in <module>
    main()
  File "map-sr.py", line 353, in main
    run_split(file_prefix,align_path,peak_path, num_threads, overwrite_files)
  File "map-sr.py", line 128, in run_split
    d =BedTool.merge(x,c = '5,6', o = 'collapse,collapse')
  File "/home/nemi/.conda/envs/ecc_finder/lib/python3.8/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/home/nemi/.conda/envs/ecc_finder/lib/python3.8/site-packages/pybedtools/bedtool.py", line 396, in wrapped
    stream = call_bedtools(
  File "/home/nemi/.conda/envs/ecc_finder/lib/python3.8/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:
 
        bedtools merge -o collapse,collapse -i /tmp/pybedtools._dwf99vj.tmp -c 5,6
 
Error message was:
Error: line number 279715765 of file /tmp/pybedtools._dwf99vj.tmp has 4 fields, but 6 were expected.
```

Do you have any idea how to debug it? I have enough disk space. My quota is >130 TB, so it is unlikely that the output was truncated due to the lack of space. 

I will be grateful for the feedback. 

Have a nice evening!

Best,
Nemi

**Comment by njaupan** [comment]
Hi Nemi,

I totally agree that it is not RAM problem, but the intermedate file was empty for the 6th column so the bedtools merge did not work. There are places to dig in the script, but the data in question makes it easier. Could you please send me a random subset of your raw reads (njaupanpan@gmail.com) so I can take a look?

Best,
Panpan

**Comment by inud3mon** [comment]
Hi Panpan,

I actually have the same problem as above - the code will not even run with the test Arabidopsis samples provide. It always crashes at the same point 

bedtools merge -o collapse,collapse -i /tmp/.........-c 5,6

How can I fix this issue please?

Hi @nemitheasura I was also wondering if you were able to get past this issue?

Thanks,

Jenn

**Comment by Li-jiale** [comment]
Hi Panpan,
When I use the software for analysis, I am also stuck at the "Detect split reads step" and the fa, csv and png files are missing. I don't know where the problem lies. In addition, I have seen articles that use scATAC data and ecc_finder for analysis, and I wonder if this is reasonable. In addition, I also want to know whether the data input to ecc_finder needs to be filtered, because I noticed that there seems to be a step to filter the data when running the code.
Thanks,
Jiale

**Comment by julia-luz** [comment]
Hey there Jiale! I'm not Dr. Panpan, but I'll try to help!


> Hi Panpan, When I use the software for analysis, I am also stuck at the "Detect split reads step" and the fa, csv and png files are missing. I don't know where the problem lies. 

Would you mind sharing the full error? How big is your reference index file? If it's over 4GB you might need to use the `-g yes` option. 

> In addition, I have seen articles that use scATAC data and ecc_finder for analysis, and I wonder if this is reasonable. 

Forgive me as I'm not an expert, but to me this seems a bit odd, as ecc_finder is meant to take data that has already been enriched for circularized DNA molecules. How is this being achieved while using scATAC ? 

> In addition, I also want to know whether the data input to ecc_finder needs to be filtered, because I noticed that there seems to be a step to filter the data when running the code. 

I'm not entirely sure I understand your question. Would you like to know what the filtering step does within the pipeline? It filters the results in the table based on the parameters set. If you're asking if you need to filter after the code has already been run, I believe it would depend on your objectives. Maybe you only want those eccDNAs that map to a certain area of the genome, or some other characteristic that's not within the parameters you can set here.

**Comment by Li-jiale** [comment]
Dear Luz @julia-luz，

Thank you very much for your reply!!!

And I will try to use "-g" when the data is larger than 4G as you said. These days, I tried to extract the ecc.sr.bam.bed file from align_files using Linux, and followed the operation of the source code in map-sr.py for subsequent analysis. I successfully obtained two files, ecc.sr.split.num.bed and ecc.sr.disc.num.bed, but encountered difficulties in screening.

I saw in the article "ecc_finder: A Robust and Accurate Tool for Detecting Extrachromosomal Circular DNA From Sequencing Data” that the screening of ECCDNA loci is based on Confidence Score. Confidence Score is determined by "discordant and splits reads at the locus and the coverage at the locus boundaries". However, I did not find a suitable threshold for screening coverage in the code and article. I would like to know what is the appropriate threshold for this coverage. In addition, the article’s “Supplementary Figure 2” also mentions that the ECCDNA site also needs to be screened through “even distribution of split and discordant reads”. I would like to ask if this refers to the Confidence Score.

Regarding the application of ecc_finder to analyze scATAC data, I read the article "Investigating cellular heterogeneity at the single-cell level by the flexible and mobile extrachromosomal circular DNA". In the article, the split and disc reads detected by ecc_finder are traced back to specific cells through barcodes so that differences can be found between cells with and without eccDNA. I am curious about the rationality of doing so.

Regarding data filtering, because some sequencing data reads do not meet the standards, for example, many bases are not measured and are represented by "N", these reads are generally removed during conversion. I am curious whether this step is required when using ecc_finder.

Once again, thank you very much for your reply. Wish you a nice day.

Jiale

$ python ecc_finder.py map-sr /mnt/lijiale_new/NRF2_qc/reference.sr.idx /mnt/lijiale_new/NRF2_qc/SRR_1_val_1.fq.gz /mnt/lijiale_new/NRF2_qc/SRR_2_val_2.fq.gz -r /mnt/lijiale_new/database/genome/Ensembl/Homo_sapiens/GRCh_release113/Homo_sapiens.GRCh38.dna.primary_assembly.fa --aligner minimap2
Tue Feb 25 07:30:29 2025 --- VERSION: ecc_finder v1.0.0
Tue Feb 25 07:30:29 2025 --- CMD: python ecc_finder.py map-sr /mnt/lijiale_new/NRF2_qc/reference.sr.idx /mnt/lijiale_new/NRF2_qc/SRR_1_val_1.fq.gz /mnt/lijiale_new/NRF2_qc/SRR_2_val_2.fq.gz -r /mnt/lijiale_new/database/genome/Ensembl/Homo_sapiens/GRCh_release113/Homo_sapiens.GRCh38.dna.primary_assembly.fa --aligner minimap2
Tue Feb 25 07:30:29 2025 --- INFO: Remove adapter
Tue Feb 25 07:30:29 2025 --- INFO: Retaining pre-existing file: /mnt/lijiale_new/biosoft/ecc_finder/eccFinder_output/align_files/ecc.sr.html
Tue Feb 25 07:30:29 2025 --- INFO: Align the query raw read to the reference
Tue Feb 25 07:30:29 2025 --- INFO: Retaining pre-existing file: /mnt/lijiale_new/biosoft/ecc_finder/eccFinder_output/align_files/ecc.sr.sam
Tue Feb 25 07:30:29 2025 --- INFO: Sort the alignments
Tue Feb 25 07:30:29 2025 --- INFO: Retaining pre-existing file: /mnt/lijiale_new/biosoft/ecc_finder/eccFinder_output/align_files/ecc.sr.bam
Tue Feb 25 07:30:29 2025 --- INFO: Check read pair and read pair orientation
Tue Feb 25 07:30:29 2025 --- INFO: Retaining pre-existing file: /mnt/lijiale_new/biosoft/ecc_finder/eccFinder_output/align_files/ecc.sr.bam.bed
Tue Feb 25 07:30:29 2025 --- INFO: Detecting sites of genomic enrichment
Tue Feb 25 07:30:29 2025 --- INFO: Retaining pre-existing file: /mnt/lijiale_new/biosoft/ecc_finder/eccFinder_output/ecc.sr.site.bed
Tue Feb 25 07:30:29 2025 --- INFO: Detect split reads 
（The operation will stop automatically here.）
